#!/bin/bash
################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 1.05
##  \   \         Application : VIO v1.05_a Core
##  /   /         Filename : ise_implement.sh
## /___/   /\     
## \   \  /  \
##  \___\/\___\
##
##
## ise_implement.sh script 
## Generated by Xilinx VIO v1.05_a Core
##
#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the VIO core
#-----------------------------------------------------------------------------
#Exit on Error enabled.
set -o errexit

#Create results directory
rm -rf results
mkdir results
echo 'Running coregen on chipscope_icon required for example design'
coregen -b chipscope_icon.xco -p coregen.cgp
# Check Results
if [ $? -gt 0 ] ; then 
echo An error occurred running coregen on chipscope_icon
echo FAIL
exit
fi

cp ../../vio_1.ngc .

##-------------------------------Run Xst on Example design----------------------------
echo 'Running Xst on example design'
xst -ifn example_vio_1.xst -ofn example_core.log -intstyle silent
# Check Results
if [ $? -gt 0 ] ; then 
echo An error occurred running XST on example_vio_1
echo FAIL
exit
fi
cp chipscope_icon.ngc ./results
cp ../../vio_1.ngc        ./results
cp example_vio_1.ngc        ./results
cp chipscope_icon.ncf ./results
cp ../../vio_1.ncf        ./results
cd ./results
##-------------------------------Run ngdbuild---------------------------------------
echo 'Running ngdbuild'
ngdbuild -uc ../../example_design/example_vio_1.ucf -p xc7a100t-csg324-3 -sd . example_vio_1.ngc example_vio_1.ngd
if [ $? -gt 0 ] ; then 
echo An error occurred running NGDBUILD on example_vio_1 
echo FAIL
exit
fi
#end run ngdbuild section
##-------------------------------Run map-------------------------------------------
echo 'Running map'
map -w -p xc7a100t-csg324-3 -o example_vio_1.map.ncd example_vio_1.ngd
if [ $? -gt 0 ] ; then 
echo An error occurred running MAP on example_vio_1 
echo FAIL
exit
fi
##-------------------------------Run par-------------------------------------------
echo 'Running par'
par -w -ol high example_vio_1.map.ncd example_vio_1.ncd 
if [ $? -gt 0 ] ; then 
echo An error occurred running PAR on example_vio_1 
echo FAIL
exit
fi
##---------------------------Report par results-------------------------------------
echo 'Running design through bitgen'
bitgen -d -g GWE_cycle:Done -g GTS_cycle:Done -g DriveDone:Yes -g StartupClk:Cclk -w example_vio_1.ncd
if [ $? -gt 0 ] ; then 
echo An error occurred running BITGEN on example_vio_1 
echo FAIL
exit
else
echo PASS
exit
fi
