################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 1.06
##  \   \         Application : ICON v1.06_a Core
##  /   /         Filename : pa_rdi_implement.tcl
## /___/   /\     
## \   \  /  \
##  \___\/\___\
##
##
## pa_rdi_implement.tcl script 
## Generated by Xilinx ICON v1.06_a Core
##
#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the ICON core
#-----------------------------------------------------------------------------
add_files -norecurse {../example_design/example_icon_1.vhd}
import_ip -file {chipscope_vio.xco} -name chipscope_vio
generate_target { all } [get_ips chipscope_vio]
set_property top example_icon_1 [get_filesets sources_1]
set_property target_constrs_file {../example_design/example_icon_1.xdc} [current_fileset -constrset]
set_property flow {RDS 13} [get_runs synth_1]
set_property flow {RDI 13} [get_runs impl_1]
set_property used_in_synthesis false [get_files icon_1.xdc]
synth_design
place_design
route_design
write_bitstream -force example_design.bit
